### ISSUE TITLE
Add website link to repo

### ISSUE THREAD

**Issue by ThisIsMissEm** [tgthorley/Safety-and-Wellbeing-for-Researchers-and-Practitioners#26]
Hey, this looks like a really neat resource. Can I suggest adding the "website" field on the repository such that people finding the repository can find the published site? 

https://tgthorley.github.io/Safety-and-Wellbeing-for-Researchers-and-Practitioners/

Docs are kinda here for how to do that if you need them: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by tgthorley** [comment]
Thanks @ThisIsMissEm ! 

Done!
